### ISSUE TITLE
Should SaaS be part of the software categorization? 

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/scer#10]
## Question: Should SaaS (Software s a Service) be part of the software categorization? 
It most likely is part of the software categorization for the SCER purpose, such as music streaming service. SCER really means software induced carbon efficiency rating - meaning, the carbon efficiencies due to running of the software application, regardless if the software is run as a service, or run on a desktop.

**Comment by seanmcilroy29** [comment]
From: Charlene WONG -  Yes, for us, we have included SaaS as part of software categorisation as the deployment of these software can and will affect the carbon efficiency. They are also a key generator if there is a huge adoption of users.

**Comment by chrisxie-fw** [comment]
It is generally agreed YES.
