### ISSUE TITLE
Common Components of a Software Categorization (2.1.1) should also include "Size of the Software" as one of the other aspects. 

### ISSUE THREAD

**Issue by KeertiHCL** [Green-Software-Foundation/scer#26]
### "2.1.1 Common Components of a Software Categorization"

I think this should also include - **"Size of the Software"** as a common component for the software categorization. 
Because many software setups are comparatively very big in size than others and thus, comparatively they also acquire much more storage space(s). And that is one of the important reasons for carbon emissions.

**Comment by chrisxie-fw** [comment]
This sounds much more accurate for Large Language Models (LLMs) where the larger the LLM, the more potential for more energy usage and larger carbon footprint. But for general purpose software, like browsers, OS's, size of the software may not necessarily correlate to its efficiency. For instance, a java program can be compiled with or without optimization (e.g. Just in time compiler, or JIT). Even though the resulting binary code size is the same, the performance could be drastically different, regardless of the size of the software. But I do agree that the **"Size of the Software"** could be part of the **"Extended Components of a Software Categorization"**.

**Comment by chrisxie-fw** [comment]
@KeertiHCL will update the base document with "Size of Software" as an extended component of a Software Categorization".
