### ISSUE TITLE
Rating Example needs some correction

### ISSUE THREAD

**Issue by KeertiHCL** [Green-Software-Foundation/scer#27]
This doesn't look correct or a bit confusing -

![scer](https://github.com/Green-Software-Foundation/scer/assets/50625421/1d7da74a-dd3a-4f41-ac2d-bb0f972a9f83)

**In the rating scale:** It's written "SCI scores above the 90th percentile", but I think it should be "Percentile Position above the 90th percentile"?

**Comment by chrisxie-fw** [comment]
good catch, fixed!
