### ISSUE TITLE
Add a license.md to SCER repository

### ISSUE THREAD

**Issue by chrisxie-fw** [Green-Software-Foundation/scer#60]
Add a license.md to SCER repository, similar to https://github.com/Green-Software-Foundation/sci/blob/main/LICENCE.md, to indicate license and copyright terms, such as "AS-IS" term, etc, and address issues found in this pull request: https://github.com/Green-Software-Foundation/scer/pull/58 . Regardless of the above concerns, adding a license to a GitHub repository is a best practice for open source projects.

**Comment by seanmcilroy29** [comment]
License added
