### ISSUE TITLE
Create an SCER outreach and resources folder

### ISSUE THREAD

**Issue by chrisxie-fw** [Green-Software-Foundation/scer#74]
### Outline Action Item Details

Create a folder that contains a list of presentation slide decks and resources regarding SCER, for the purpose of introduction of SCER's work and projects, including external references of the SCER open source and open standard project.

**Comment by seanmcilroy29** [comment]
@chrisxie-fw - Resource folder added - https://github.com/Green-Software-Foundation/scer/tree/Dev/Resources

**Comment by chrisxie-fw** [comment]
Thank you so much @seanmcilroy29 !
